# Generated by Django 3.1.2 on 2020-12-23 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataguru',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nohp', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=225, null=True)),
                ('biaya', models.IntegerField(blank=True)),
                ('no_id', models.IntegerField()),
                ('link', models.CharField(max_length=100, null=True)),
                ('catatan', models.TextField(null=True)),
                ('foto', models.ImageField(upload_to='img/')),
                ('portofolio', models.FileField(upload_to='document/')),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('kategori', models.CharField(choices=[('silat', 'silat'), ('renang', 'renang'), ('basket', 'basket'), ('tenis meja', 'tenis meja'), ('voli', 'voli')], max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(default=True)),
                ('skil', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KtgAmpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='paket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pkt', models.IntegerField(blank=True, null=True)),
                ('id_pkt', models.IntegerField(null=True)),
                ('nama_pkt', models.CharField(max_length=200, null=True)),
                ('jml_pertemuan', models.CharField(blank=True, choices=[('1X Pertemuan', '1X Pertemuan'), ('2X Pertemuan', '2X Pertemuan'), ('3X Pertemuan', '3X Pertemuan'), ('4X Pertemuan', '4X Pertemuan')], max_length=200, null=True)),
                ('biaya', models.IntegerField(null=True)),
                ('hari_1', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=200)),
                ('jam_1', models.CharField(blank=True, choices=[('07-08 AM', '07-08 AM'), ('08-09 AM', '08-09 AM'), ('09-10 AM', '09-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM')], max_length=200)),
                ('hari_2', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=200)),
                ('jam_2', models.CharField(blank=True, choices=[('07-08 AM', '07-08 AM'), ('08-09 AM', '08-09 AM'), ('09-10 AM', '09-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM')], max_length=200)),
                ('hari_3', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=200)),
                ('jam_3', models.CharField(blank=True, choices=[('07-08 AM', '07-08 AM'), ('08-09 AM', '08-09 AM'), ('09-10 AM', '09-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM')], max_length=200)),
                ('hari_4', models.CharField(blank=True, choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu'), ('Minggu', 'Minggu')], max_length=200)),
                ('jam_4', models.CharField(blank=True, choices=[('07-08 AM', '07-08 AM'), ('08-09 AM', '08-09 AM'), ('09-10 AM', '09-10 AM'), ('10-11 AM', '10-11 AM'), ('11-12 PM', '11-12 PM')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='datamurid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
                ('nohp', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=225, null=True)),
                ('No_id', models.IntegerField()),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('tanggal_lahir', models.DateField(default=True)),
                ('pendidikan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.ktgampu')),
            ],
        ),
    ]
