# Generated by Django 3.1.2 on 2020-12-24 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataguru',
            name='biaya',
        ),
    ]
